### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by oindrilabhadra78** [dsciitpatna/SAAR-Android-Client#10]
Add CONTRIBUTING.md containing rules for making contributions

**Comment by ajirk** [comment]
Can I work on this? What to do?

**Comment by somenath1435** [comment]
@ajirk u can work on this
You need to add a contributing.md file in this repository 
You may take help from this link :-
https://github.com/fossasia/open-event-android/blob/development/CONTRIBUTING.md
