### ISSUE TITLE
Add ShareFragment

### ISSUE THREAD

**Issue by oindrilabhadra78** [dsciitpatna/SAAR-Android-Client#20]
**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by chanmol1999** [comment]
@oindrilabhadra78 Can you tell the purpose for this?

**Comment by oindrilabhadra78** [comment]
For adding social media links

**Comment by chanmol1999** [comment]
I think that they should be added in about us page.Please share your views @atm1504 @somenath1435

**Comment by atm1504** [comment]
@chanmol1999 she is doing it as per the plan. We are trying to make similar things like that of website. Moreover share fragments won't just contain shareable links, but it will be a place where our alumnus can share their views with others!
