### ISSUE TITLE
Make Button Rounded in Donate Page

### ISSUE THREAD

**Issue by somenath1435** [dsciitpatna/SAAR-Android-Client#34]
**Describe the chore**
Currently the button is rectangular, make it rounded.
Newbies are encouraged to fix this issue.
**Would you like to work on the issue?**
- [ ] Yes
- [x] No
- Other:

**Comment by Ashgo18** [comment]
I wanna work on it

**Comment by amdal07** [comment]
@Ashgo18 go ahead

**Comment by amdal07** [comment]
@Ashgo18 u made wrong changes. It affected all the related files

**Comment by Ashgo18** [comment]
Can u Please explain it ?

**Comment by chanmol1999** [comment]
Yes @Ashgo18 just you have to create a new drawable instead of changing the previous one

**Comment by somenath1435** [comment]
@Ashgo18 make changes only in donate page.... Just change into button with rounded corners
