### ISSUE TITLE
Add ScrollView in Team/Donate/Share/Contact page

### ISSUE THREAD

**Issue by somenath1435** [dsciitpatna/SAAR-Android-Client#41]
**Describe the chore**
Add ScrollView in these pages.
Check if layout is proper in landscape mode(Screen Rotation On)
**Would you like to work on the issue?**
- [ ] Yes
- [x] No
- Other:
Beginners are encouraged to fix this issue

**Comment by laxmankumarmeghwal** [comment]
I (Laxman Kumar ) want to work on this

**Comment by atm1504** [comment]
@laxmankumarmeghwal go ahead
