### ISSUE TITLE
Reduce the text size of Donate Now button

### ISSUE THREAD

**Issue by oindrilabhadra78** [dsciitpatna/SAAR-Android-Client#55]
**Describe the chore**
Make the text size of donate now button in Donate Fragment smaller.
Text size of Donate Now button should be similar to that of Login button
**Would you like to work on the issue?**
- [ ] Yes
- [x] No
- Other:

**Comment by Ashgo18** [comment]
I wanna work on it

**Comment by Ashgo18** [comment]
In login Button it's medium .
